name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies (e.g., Qt, if applicable)
        run: |
          sudo apt-get install qt6-qmake qt6-qmake-bin

      - name: Build the project
        run: |
          qmake
          make
